In [4]:
#Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np


In [6]:
a = np.arange(10)
b = a[::-1]
b


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [8]:
a = np.arange(10)
b = a[::-1]
c = np.diag(b)
print(c)
np.trace(c)


[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

In [9]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [10]:
a = np.array([[4,2,1], [1,3,0], [0,5,4]])
b = np.array([4,12,-3])
x = np.linalg.solve(a,b)
x


array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
np.allclose( np.dot(a,x), b)

True

In [12]:
# Задание 4
#Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
#next_user_stats = np.array([0, 1, 2, 0, 0, 0])
#Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [13]:
import numpy as np
users_stats_list = []
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


for i in users_stats: 
    users_stats_lenght = np.linalg.norm(i)
    next_user_stats_lenght = np.linalg.norm(next_user_stats)
    cosine = np.dot( i, next_user_stats ) / ( users_stats_lenght * next_user_stats_lenght )
    users_stats_list.append(cosine)
max_cosine = max(users_stats_list)  
print ("Самый похожий пользователь - ID:", users_stats_list.index(max_cosine))

Самый похожий пользователь - ID: 7
